// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKGwMNhpob3k8dic0e4TZaBfU_-sf7NQ',
    appId: '1:1079080235734:web:30b6d5c172c8dd6472cf77',
    messagingSenderId: '1079080235734',
    projectId: 'stopwacth-6d6c5',
    authDomain: 'stopwacth-6d6c5.firebaseapp.com',
    storageBucket: 'stopwacth-6d6c5.appspot.com',
    measurementId: 'G-8Y457N13QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUAUet_7MncsedJVFVyXVF5SXvcCASZE0',
    appId: '1:1079080235734:android:36ecf61e699ce9bb72cf77',
    messagingSenderId: '1079080235734',
    projectId: 'stopwacth-6d6c5',
    storageBucket: 'stopwacth-6d6c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWbI1hXEXbbshkdTNhM1U5RwlZzO3EMI',
    appId: '1:1079080235734:ios:7046a08a8cc1afdf72cf77',
    messagingSenderId: '1079080235734',
    projectId: 'stopwacth-6d6c5',
    storageBucket: 'stopwacth-6d6c5.appspot.com',
    iosBundleId: 'com.example.latihanFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWbI1hXEXbbshkdTNhM1U5RwlZzO3EMI',
    appId: '1:1079080235734:ios:7046a08a8cc1afdf72cf77',
    messagingSenderId: '1079080235734',
    projectId: 'stopwacth-6d6c5',
    storageBucket: 'stopwacth-6d6c5.appspot.com',
    iosBundleId: 'com.example.latihanFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPKGwMNhpob3k8dic0e4TZaBfU_-sf7NQ',
    appId: '1:1079080235734:web:d9002ca3adc82ddf72cf77',
    messagingSenderId: '1079080235734',
    projectId: 'stopwacth-6d6c5',
    authDomain: 'stopwacth-6d6c5.firebaseapp.com',
    storageBucket: 'stopwacth-6d6c5.appspot.com',
    measurementId: 'G-6VQ224BD2C',
  );
}
